export const SET_USERNAME = 'SET_USERNAME'

export const RENDER_TODOS = 'RENDER_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const MARK_DONE = 'MARK_DONE'
export const MARK_ALL_DONE = 'MARK_ALL_DONE'
export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_SELECTED = 'DELETE_SELECTED'
export const FILTER_TODOS = 'FILTER_TODOS'

export const CHOOSE_FILTER_DROPDOWN = 'CHOOSE_FILTER_DROPDOWN'

export const CHOOSE_PRIORITY_DROPDOWN = 'CHOOSE_PRIORITY_DROPDOWN'
export const RESET_PRIORITY_DROPDOWN = 'RESET_PRIORITY_DROPDOWN'

export const RENDER_CATEGORY_DROPDOWN = 'RENDER_CATEGORY_DROPDOWN'
export const CHOOSE_CATEGORY_DROPDOWN = 'CHOOSE_CATEGORY_DROPDOWN'
export const ADD_CATEGORY_DROPDOWN = 'ADD_CATEGORY_DROPDOWN'
export const RESET_CATEGORY_DROPDOWN = 'RESET_CATEGORY_DROPDOWN'

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION'

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE'
export const SET_ITEMS_TO_SHOW_COUNT = 'SET_ITEMS_TO_SHOW_COUNT'
export const SHOW_ALERT = 'SHOW_ALERT'
export const CLOSE_ALERT = 'CLOSE_ALERT'
export const CHOOSE_ACTIVE_CATEGORY = 'CHOOSE_ACTIVE_CATEGORY'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'